# Python Básico

## Inicio

In [ ]:
print('hola mundo')

hola mundo


In [ ]:
!ls

sample_data


In [ ]:
!uname -a

Linux c6062f2f4edd 4.19.112+ #1 SMP Thu Jul 23 08:00:38 PDT 2020 x86_64 x86_64 x86_64 GNU/Linux


## Tipos de Datos

<table>
  <tr>
    <td>Variable</td>
    <td>Valor</td>
  </tr>
  <tr>
    <td>String</td>
    <td>'valor'</td>
  </tr>
  <tr>
    <td>Int</td>
    <td>5</td>
  </tr>
  <tr>
    <td>Float</td>
    <td>5.3</td>
  </tr>
</table>

In [ ]:
variable1 = 'hola'
print(variable1)

hola


In [ ]:
variable1 = 3.5
print(variable1)

3.5


In [ ]:
print(type(variable1))

<class 'float'>


In [ ]:
type(variable1)

float

In [ ]:
# Boolean Type: True // False
print(type(True)) 

<class 'bool'>


In [ ]:
variable = 4.2
variable = int(variable)
print(variable)
print(type(variable))

4
<class 'int'>


In [ ]:
print("Hola")
print('Hola x2')

Hola
Hola x2


Como usar comillas en strings

In [ ]:
print("Hola 'SPS'")
print('Hola "SPS" x2')

Hola 'SPS'
Hola "SPS" x2


## Operadores

In [ ]:
print(5 - 4)
print(5 + 4)
print(5 * 4)
print(5 / 4)

1
9
20
1.25


In [ ]:
# Division entera
print(5 // 4)
# Modulo
print(14 % 4)
# Exp
print(2 ** 3)

1
2
8


## Listas

In [ ]:
lista = list()
lista = []

In [ ]:
lista = [2, 3.5, 'hola', 8, 5, 7, 9]

In [ ]:
print(type(lista))

<class 'list'>


In [ ]:
print(len(lista))

7


In [ ]:
# [1;3>
print(lista[1:3])

[3.5, 'hola']


In [ ]:
print(lista[-6:-4])

[3.5, 'hola']


## If, For, While

In [ ]:
var = 11

if var > 5:
  # codigo
  print("mayor que 5")
else:
  # otro codigo
  print("menor que 5")

mayor que 5


In [ ]:
lista

[2, 3.5, 'hola', 8, 5, 7, 9]

In [ ]:
for i in lista:
  print(i)

2
3.5
hola
8
5
7
9


In [ ]:
for i in range(8):
  print(i + 5)

5
6
7
8
9
10
11
12


In [ ]:
var = 5

while var >= 0:
  print(var)
  # var = var - 1
  var -= 1

5
4
3
2
1
0


## Funciones

In [ ]:
def primera_funcion(x):
  return x ** 2

In [ ]:
new_var = primera_funcion(6)

In [ ]:
new_var

36

In [ ]:
def segunda_funcion(x, y):
  z = x *y + x
  return z

In [ ]:
segunda_funcion(4,3)

16

## Entrada de valores

In [ ]:
dato_ingreso = input('Ingresa algo: ')

Ingresa algo: 59


In [ ]:
dato_ingreso

'59'

In [ ]:
type(dato_ingreso)

str

## Librerías

Ver en que carpeta estoy

In [ ]:
!pwd

/content


Listar los archivos/carpetas que hay dentro

In [ ]:
!ls

sample_data


In [ ]:
%ls

sample_data/


In [ ]:
100_000

100000

In [ ]:
%%time
valor = 0
for i in range(100_000_000):
  # valor = valor + 1
  valor += 1
print(valor)

100000000
CPU times: user 9.86 s, sys: 1.48 ms, total: 9.86 s
Wall time: 9.87 s


In [ ]:
%%writefile archivo.txt
Cualquier cosa

Writing archivo.txt


In [ ]:
%ls

archivo.txt  sample_data/


In [ ]:
# cat para abrir archivo
!cat archivo.txt

Cualquier cosa

In [ ]:
%%writefile mimod.py
def suma(x, y):
  return x + y

def mult(x, y):
  return x * y

Overwriting mimod.py


In [ ]:
!cat mimod.py

def suma(x, y):
  return x + y

def mult(x, y):
  return x * y

Importar modulo

In [ ]:
import mimod as mm

In [ ]:
mimod.suma(5, 3)

8

In [ ]:
mimod.mult(5, 3)

15

In [ ]:
mm.mult(6,8)

48

# Numpy

In [ ]:
import numpy as np

In [ ]:
np.array([2, 4, 6])

array([2, 4, 6])

In [ ]:
np.array([[2, 4, 6], [3, 5, 7]])

array([[2, 4, 6],
       [3, 5, 7]])

In [ ]:
vector = np.array([2, 4, 6])

In [ ]:
matriz = np.array([[2, 4, 6], [3, 5, 7]])

In [ ]:
type(vector)

numpy.ndarray

In [ ]:
type(matriz)

numpy.ndarray

In [ ]:
vector.ndim , matriz.ndim

(1, 2)

In [ ]:
matriz.shape

(2, 3)

In [ ]:
matriz = np.array([[2, 4, 6], 
                   [3, 5, 7],
                   [4, 6, 8]])

In [ ]:
matriz

array([[2, 4, 6],
       [3, 5, 7],
       [4, 6, 8]])

In [ ]:
vector = np.array([2.0, 4.5, 6.2])

In [ ]:
vector.dtype

dtype('float64')

In [ ]:
matriz + matriz

array([[ 4,  8, 12],
       [ 6, 10, 14],
       [ 8, 12, 16]])

In [ ]:
4 * matriz

array([[ 8, 16, 24],
       [12, 20, 28],
       [16, 24, 32]])

In [ ]:
matriz

array([[2, 4, 6],
       [3, 5, 7],
       [4, 6, 8]])

In [ ]:
vector

array([2. , 4.5, 6.2])

In [ ]:
matriz + vector

array([[ 4. ,  8.5, 12.2],
       [ 5. ,  9.5, 13.2],
       [ 6. , 10.5, 14.2]])

In [ ]:
np.zeros((4,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
vector

array([2. , 4.5, 6.2])

In [ ]:
vector.shape

(3,)

In [ ]:
matriz

array([[2, 4, 6],
       [3, 5, 7],
       [4, 6, 8]])

In [ ]:
matriz.shape

(3, 3)

In [ ]:
np.dot(matriz, vector).shape

(3,)

In [ ]:
new_vector = np.reshape(vector, (1,3))

In [ ]:
new_vector.shape

(1, 3)

In [ ]:
new_vector = np.reshape(vector, (3,1))

In [ ]:
new_vector.shape

(3, 1)

In [ ]:
new_vector

array([[2. ],
       [4.5],
       [6.2]])

In [ ]:
np.dot(matriz, new_vector).shape

(3, 1)

In [ ]:
 val_matrix = np.random.randn(8,7)

In [ ]:
np.reshape(val_matrix, (4,-1)).shape

(4, 14)

In [ ]:
np.arange(2,14).reshape(6,-1)

array([[ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13]])

In [ ]:
matriz

array([[2, 4, 6],
       [3, 5, 7],
       [4, 6, 8]])

In [ ]:
matriz[1][1]

5