## Compresión de Listas

In [80]:
lista = [3, 4, 6, 7, 'hola']

In [81]:
for valor in lista:
  print(valor)

3
4
6
7
hola


In [84]:
for valor in range(2, 8, 2):
  print(valor)

2
4
6


In [85]:
for valor in range(2, 8, 2):
  lista.append(valor)

In [86]:
lista

[3, 4, 6, 7, 'hola', 2, 4, 6]

In [93]:
[valor for valor in range(6)]

[0, 1, 2, 3, 4, 5]

In [94]:
[valor for valor in range(6) if valor > 3]

[4, 5]

In [95]:
[valor**2 for valor in range(6) if valor > 3]

[16, 25]

In [91]:
listac = [valor for valor in [x for x in range(8)] if valor % 2 == 0]

In [92]:
listac

[0, 2, 4, 6]

## Diccionarios

In [25]:
diccionario = dict()
type(diccionario)

dict

In [26]:
diccionario = {}
type(diccionario)

dict

In [30]:
diccionario = {'Ronald': 12, 'Aaron':15, 'Jose': 7, 10: 4, 2: 'algo', 'x': [12, 13, 14]}

In [31]:
diccionario['Ronald']

12

In [32]:
diccionario

{10: 4, 2: 'algo', 'Aaron': 15, 'Jose': 7, 'Ronald': 12, 'x': [12, 13, 14]}

In [33]:
diccionario.keys()

dict_keys(['Ronald', 'Aaron', 'Jose', 10, 2, 'x'])

In [34]:
diccionario.values()

dict_values([12, 15, 7, 4, 'algo', [12, 13, 14]])

In [35]:
dict(zip([1, 2, 3], [5,10,15]))

{1: 5, 2: 10, 3: 15}

In [36]:
diccionario['nuevo_valor'] = 12341341

In [37]:
diccionario

{10: 4,
 2: 'algo',
 'Aaron': 15,
 'Jose': 7,
 'Ronald': 12,
 'nuevo_valor': 12341341,
 'x': [12, 13, 14]}

In [1]:
import numpy as np

# Pandas

In [3]:
!pip install pandas

In [2]:
import pandas as pd

In [9]:
nota = pd.Series([14, 13, 12], index = ['Aaron', 'Jose', 'Ronald'])

In [10]:
nota

Aaron     14
Jose      13
Ronald    12
dtype: int64

In [8]:
nota2 = pd.Series([14, 13, 12])
nota2

0    14
1    13
2    12
dtype: int64

In [7]:
np.array([14, 13, 12])

array([14, 13, 12])

In [11]:
nota['Aaron']

14

In [12]:
nota.dtype

dtype('int64')

In [54]:
nota = pd.Series([14, 13, 12], index = ['Aaron', 'Jose', 'Ronald'], dtype = 'int32')
nota.dtype

dtype('int32')

In [15]:
nota = pd.Series([14, 'NSP', 12], index = ['Aaron', 'Jose', 'Ronald'])

In [16]:
nota

Aaron      14
Jose      NSP
Ronald     12
dtype: object

In [17]:
np.linspace(3, 7, 4)

array([3.        , 4.33333333, 5.66666667, 7.        ])

In [18]:
x = np.linspace(3, 7, 4)

In [20]:
nota3 = pd.Series(x, index = ['Aaron', 'Jose', 'Ronald', 'Alex'])

In [21]:
nota3

Aaron     3.000000
Jose      4.333333
Ronald    5.666667
Alex      7.000000
dtype: float64

In [38]:
x = {'Cristian' : 12, 'Carlos': 15}
nota4 = pd.Series(x)
nota4

Cristian    12
Carlos      15
dtype: int64

In [41]:
x = {'Cristian' : 12, 'Carlos': 15}
nota4 = pd.Series(x, index = ['Aaron', 'Cristian', 'Carlos', 'Jose'])
nota4

Aaron        NaN
Cristian    12.0
Carlos      15.0
Jose         NaN
dtype: float64

In [42]:
nota4.index

Index(['Aaron', 'Cristian', 'Carlos', 'Jose'], dtype='object')

In [43]:
nota4.values

array([nan, 12., 15., nan])

In [45]:
nota4['Carlos']

15.0

In [46]:
nota4[2]

15.0

In [47]:
nota4

Aaron        NaN
Cristian    12.0
Carlos      15.0
Jose         NaN
dtype: float64

In [48]:
nota4.name = 'SPS 2020'

In [49]:
nota4

Aaron        NaN
Cristian    12.0
Carlos      15.0
Jose         NaN
Name: SPS 2020, dtype: float64

In [50]:
nota4.index.name = 'Alumnos'

In [51]:
nota4

Alumnos
Aaron        NaN
Cristian    12.0
Carlos      15.0
Jose         NaN
Name: SPS 2020, dtype: float64

In [52]:
nota4.axes

[Index(['Aaron', 'Cristian', 'Carlos', 'Jose'], dtype='object', name='Alumnos')]

In [55]:
nota

Aaron     14
Jose      13
Ronald    12
dtype: int32

In [56]:
nota.astype('float64')

Aaron     14.0
Jose      13.0
Ronald    12.0
dtype: float64

In [57]:
nota

Aaron     14
Jose      13
Ronald    12
dtype: int32

In [58]:
if True:
  print('Algo')

Algo


In [60]:
dias = pd.Series([31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31], 
                 index = ['Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun', 'Jul', 'Ago', 'Set', 'Oct', 'Nov', 'Dic']
                 )
dias

Ene    31
Feb    28
Mar    31
Abr    30
May    31
Jun    30
Jul    31
Ago    31
Set    30
Oct    31
Nov    30
Dic    31
dtype: int64

In [63]:
dias.head(8)

Ene    31
Feb    28
Mar    31
Abr    30
May    31
Jun    30
Jul    31
Ago    31
dtype: int64

In [64]:
dias.tail(3)

Oct    31
Nov    30
Dic    31
dtype: int64

In [69]:
dias.sample(4)

Mar    31
Nov    30
Jun    30
Set    30
dtype: int64

In [70]:
dias.value_counts()

31    7
30    4
28    1
dtype: int64

In [71]:
x = pd.Series([5, 1, 3, 4, np.nan, 7, 6, 5, 1, 2, 4, 3, 1, 2, np.nan, 1, 2])
x

0     5.0
1     1.0
2     3.0
3     4.0
4     NaN
5     7.0
6     6.0
7     5.0
8     1.0
9     2.0
10    4.0
11    3.0
12    1.0
13    2.0
14    NaN
15    1.0
16    2.0
dtype: float64

In [73]:
x.value_counts(dropna = False)

1.0    4
2.0    3
NaN    2
4.0    2
3.0    2
5.0    2
6.0    1
7.0    1
dtype: int64

In [74]:
x.value_counts(bins = 3)

(0.993, 3.0]    9
(3.0, 5.0]      4
(5.0, 7.0]      2
dtype: int64

In [75]:
x.value_counts(normalize = True)

1.0    0.266667
2.0    0.200000
4.0    0.133333
3.0    0.133333
5.0    0.133333
6.0    0.066667
7.0    0.066667
dtype: float64

In [76]:
x.value_counts(normalize = True, dropna= False)

1.0    0.235294
2.0    0.176471
NaN    0.117647
4.0    0.117647
3.0    0.117647
5.0    0.117647
6.0    0.058824
7.0    0.058824
dtype: float64

In [77]:
x

0     5.0
1     1.0
2     3.0
3     4.0
4     NaN
5     7.0
6     6.0
7     5.0
8     1.0
9     2.0
10    4.0
11    3.0
12    1.0
13    2.0
14    NaN
15    1.0
16    2.0
dtype: float64

In [78]:
x[2:7]

2    3.0
3    4.0
4    NaN
5    7.0
6    6.0
dtype: float64

In [79]:
x[[1,4,5,14]]

1     1.0
4     NaN
5     7.0
14    NaN
dtype: float64

In [98]:
x[[valor for valor in range(6) if valor%2 == 0]]

0    5.0
2    3.0
4    NaN
dtype: float64

In [97]:
dias

Ene    31
Feb    28
Mar    31
Abr    30
May    31
Jun    30
Jul    31
Ago    31
Set    30
Oct    31
Nov    30
Dic    31
dtype: int64

In [99]:
dias.loc[['Ene', 'Oct']]

Ene    31
Oct    31
dtype: int64

In [102]:
dias.loc['Mar': 'Oct']

Mar    31
Abr    30
May    31
Jun    30
Jul    31
Ago    31
Set    30
Oct    31
dtype: int64

In [104]:
dias.iloc[[3, 5]]

Abr    30
Jun    30
dtype: int64

In [106]:
dias.iloc[3: 9]

Abr    30
May    31
Jun    30
Jul    31
Ago    31
Set    30
dtype: int64

In [107]:
dias[dias > 30]

Ene    31
Mar    31
May    31
Jul    31
Ago    31
Oct    31
Dic    31
dtype: int64

In [108]:
dias > 30

Ene     True
Feb    False
Mar     True
Abr    False
May     True
Jun    False
Jul     True
Ago     True
Set    False
Oct     True
Nov    False
Dic     True
dtype: bool

In [110]:
dias[[True, False, False, True, True, False, False, True, True, False, False, True]]

Ene    31
Abr    30
May    31
Ago    31
Set    30
Dic    31
dtype: int64

In [111]:
dias[dias == 30]

Abr    30
Jun    30
Set    30
Nov    30
dtype: int64

### DataFrame

In [112]:
nota = pd.DataFrame({"Control" : [12, 13, 14, 16],
                     "Progra" : [16, 7, 9, 12],
                     "Fisica": [7, 6, 5, 16]}
                    )
nota

Control  Progra  Fisica
0       12      16       7
1       13       7       6
2       14       9       5
3       16      12      16

In [113]:
notas = pd.DataFrame({"Control" : [12, 13, 14, 16],
                     "Progra" : [16, 7, 9, 12],
                     "Fisica": [7, 6, 5, 16],
                     "Aprobado": ['Si', 'No', 'No', 'Si']},
                     index = ['Carlos', 'Cristian', 'Jose', 'Abraham']
                    )
notas

Control  Progra  Fisica Aprobado
Carlos         12      16       7       Si
Cristian       13       7       6       No
Jose           14       9       5       No
Abraham        16      12      16       Si

In [116]:
matrix = np.array([[1, 2, 3, 4],
          [4, 5, 6, 7],
          [8, 9, 10, 11],
          [12, 13, 14, 15]])

In [117]:
matrix

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [119]:
df1 = pd.DataFrame(matrix, index = ['A', 'B', 'C', 'D'], columns = ['Fisica', 'Quimica', 'Calculo', 'Estadistica'])
df1

Fisica  Quimica  Calculo  Estadistica
A       1        2        3            4
B       4        5        6            7
C       8        9       10           11
D      12       13       14           15

In [120]:
df1.index.name = 'Seccion'
df1.columns.name = 'Cursos'

In [121]:
df1

Cursos   Fisica  Quimica  Calculo  Estadistica
Seccion                                       
A             1        2        3            4
B             4        5        6            7
C             8        9       10           11
D            12       13       14           15

In [122]:
df1.axes

[Index(['A', 'B', 'C', 'D'], dtype='object', name='Seccion'),
 Index(['Fisica', 'Quimica', 'Calculo', 'Estadistica'], dtype='object', name='Cursos')]

In [126]:
jhoel = {'Fisica': 12, 'Quimica': 9, 'Calculo': 12}
carlos = {'Fisica': 14, 'Quimica': 12, 'Calculo': 18}
cristian = {'Fisica': 10, 'Quimica': 19, 'Calculo': 10, 'Tele': 13}

In [127]:
df_notas = pd.DataFrame([jhoel, carlos, cristian], index = ['Jhoel', 'Carlos', 'Cristian'])

In [128]:
df_notas

Fisica  Quimica  Calculo  Tele
Jhoel         12        9       12   NaN
Carlos        14       12       18   NaN
Cristian      10       19       10  13.0

In [129]:
df_notas.dtypes

Fisica       int64
Quimica      int64
Calculo      int64
Tele       float64
dtype: object

In [132]:
df_notas.head(2)

Fisica  Quimica  Calculo  Tele
Jhoel       12        9       12   NaN
Carlos      14       12       18   NaN

In [133]:
df_notas.tail(2)

Fisica  Quimica  Calculo  Tele
Carlos        14       12       18   NaN
Cristian      10       19       10  13.0

In [134]:
df_notas.sample(2)

Fisica  Quimica  Calculo  Tele
Carlos      14       12       18   NaN
Jhoel       12        9       12   NaN

In [135]:
df_notas.describe()

Fisica    Quimica    Calculo  Tele
count     3.0   3.000000   3.000000   1.0
mean     12.0  13.333333  13.333333  13.0
std       2.0   5.131601   4.163332   NaN
min      10.0   9.000000  10.000000  13.0
25%      11.0  10.500000  11.000000  13.0
50%      12.0  12.000000  12.000000  13.0
75%      13.0  15.500000  15.000000  13.0
max      14.0  19.000000  18.000000  13.0

In [136]:
df_notas.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, Jhoel to Cristian
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   Fisica   3 non-null      int64  
 1   Quimica  3 non-null      int64  
 2   Calculo  3 non-null      int64  
 3   Tele     1 non-null      float64
dtypes: float64(1), int64(3)
memory usage: 200.0+ bytes


In [138]:
df_notas.shape

(3, 4)

In [137]:
df_notas['Fisica']

Jhoel       12
Carlos      14
Cristian    10
Name: Fisica, dtype: int64

In [139]:
df_notas[df_notas['Fisica'] > 10]

Fisica  Quimica  Calculo  Tele
Jhoel       12        9       12   NaN
Carlos      14       12       18   NaN

In [141]:
df_notas[['Fisica', 'Calculo']]

Fisica  Calculo
Jhoel         12       12
Carlos        14       18
Cristian      10       10

In [142]:
type(df_notas[['Fisica', 'Calculo']])

pandas.core.frame.DataFrame

In [143]:
type(df_notas['Fisica'])

pandas.core.series.Series

In [144]:
df_notas[['Fisica']]

Fisica
Jhoel         12
Carlos        14
Cristian      10

In [146]:
type(df_notas[['Fisica']])

pandas.core.frame.DataFrame

In [148]:
df_notas[['Fisica']].info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, Jhoel to Cristian
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Fisica  3 non-null      int64
dtypes: int64(1)
memory usage: 128.0+ bytes


In [150]:
df_notas

Fisica  Quimica  Calculo  Tele
Jhoel         12        9       12   NaN
Carlos        14       12       18   NaN
Cristian      10       19       10  13.0

In [149]:
df_notas.iloc[0]

Fisica     12.0
Quimica     9.0
Calculo    12.0
Tele        NaN
Name: Jhoel, dtype: float64

In [151]:
df_notas.iloc[-1]

Fisica     10.0
Quimica    19.0
Calculo    10.0
Tele       13.0
Name: Cristian, dtype: float64

In [152]:
df_notas.iloc[-1]['Tele']

13.0

In [155]:
df_notas.iloc[:, 1]

Jhoel        9
Carlos      12
Cristian    19
Name: Quimica, dtype: int64

In [156]:
df_notas.iloc[1, 1]

12

In [157]:
df_notas.iloc[-1, 3]

13.0

In [158]:
df_notas.loc['Cristian', 'Tele']

13.0

In [159]:
df_notas.loc[['Cristian', 'Carlos'], 'Tele']

Cristian    13.0
Carlos       NaN
Name: Tele, dtype: float64

In [160]:
link = 'https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv'

In [161]:
df_iris = pd.read_csv(link)

In [162]:
df_iris.head()

sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [164]:
path = 'sample_data/california_housing_test.csv'

In [165]:
df_cal_house = pd.read_csv(path)

In [167]:
df_cal_house.tail()

longitude  latitude  ...  median_income  median_house_value
2995    -119.86     34.42  ...         1.1790            225000.0
2996    -118.14     34.06  ...         3.3906            237200.0
2997    -119.70     36.30  ...         2.2895             62000.0
2998    -117.12     34.10  ...         3.2708            162500.0
2999    -119.63     34.42  ...         8.5608            500001.0

[5 rows x 9 columns]

In [168]:
!ls drive

'My Drive'


In [169]:
path_drive = 'drive/My Drive/Charlas/data/iris.csv'

In [170]:
df_iris2 = pd.read_csv(path_drive)

In [171]:
df_iris2.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [173]:
df_iris2.head(10).T

0       1       2       3  ...       6       7       8       9
sepal_length     5.1     4.9     4.7     4.6  ...     4.6       5     4.4     4.9
sepal_width      3.5       3     3.2     3.1  ...     3.4     3.4     2.9     3.1
petal_length     1.4     1.4     1.3     1.5  ...     1.4     1.5     1.4     1.5
petal_width      0.2     0.2     0.2     0.2  ...     0.3     0.2     0.2     0.1
species       setosa  setosa  setosa  setosa  ...  setosa  setosa  setosa  setosa

[5 rows x 10 columns]

In [174]:
df_cal_house.tail().T

2995         2996  ...         2998         2999
longitude             -119.860    -118.1400  ...    -117.1200    -119.6300
latitude                34.420      34.0600  ...      34.1000      34.4200
housing_median_age      23.000      27.0000  ...      40.0000      42.0000
total_rooms           1450.000    5257.0000  ...      96.0000    1765.0000
total_bedrooms         642.000    1082.0000  ...      14.0000     263.0000
population            1258.000    3496.0000  ...      46.0000     753.0000
households             607.000    1036.0000  ...      14.0000     260.0000
median_income            1.179       3.3906  ...       3.2708       8.5608
median_house_value  225000.000  237200.0000  ...  162500.0000  500001.0000

[9 rows x 5 columns]

In [175]:
df_iris.describe()

sepal.length  sepal.width  petal.length  petal.width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [176]:
df_iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal.length  150 non-null    float64
 1   sepal.width   150 non-null    float64
 2   petal.length  150 non-null    float64
 3   petal.width   150 non-null    float64
 4   variety       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [178]:
!ls 'drive/My Drive/Charlas/data/'

iris.csv  iris.xlsx


In [179]:
df_iris_excel = pd.read_excel('drive/My Drive/Charlas/data/iris.xlsx')

In [180]:
df_iris_excel.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [181]:
%%writefile archivo.py
print('hola')

Writing archivo.py


In [182]:
!cat archivo.py

print('hola')

In [183]:
!cp archivo.py 'drive/My Drive/Charlas/data/'

In [185]:
!cp 'drive/My Drive/Charlas/data/iris.csv' .